//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoostTestAdapter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoostTestAdapter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} came from another computer and was blocked to help protect this computer..
        /// </summary>
        internal static string BadFileZone {
            get {
                return ResourceManager.GetString("BadFileZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while running test batch {0} [{1}] ({2}).
        /// </summary>
        internal static string BatchException {
            get {
                return ResourceManager.GetString("BatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid test batching strategy was found. Tests skipped..
        /// </summary>
        internal static string BatchStrategyNotFound {
            get {
                return ResourceManager.GetString("BatchStrategyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid test batching strategy was found for {0}. Source skipped..
        /// </summary>
        internal static string BatchStrategyNotFoundFor {
            get {
                return ResourceManager.GetString("BatchStrategyNotFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmdLine arguments: {0}.
        /// </summary>
        internal static string CmdLineArguments {
            get {
                return ResourceManager.GetString("CmdLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a DBGHELP instance for &apos;{0}&apos; to determine whether symbols are available..
        /// </summary>
        internal static string CouldNotCreateDbgHelp {
            get {
                return ResourceManager.GetString("CouldNotCreateDbgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate debug symbols for &apos;{0}&apos;. To make use of &apos;--list_content&apos; discovery, ensure that debug symbols are available or make use of &apos;&lt;ForceListContent&gt;&apos; via a .runsettings file..
        /// </summary>
        internal static string CouldNotLocateDebugSymbols {
            get {
                return ResourceManager.GetString("CouldNotLocateDebugSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging:   -&gt; [{0}].
        /// </summary>
        internal static string Debugging {
            get {
                return ResourceManager.GetString("Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain debugging properties for {0}..
        /// </summary>
        internal static string DebuggingPropertiesNotFound {
            get {
                return ResourceManager.GetString("DebuggingPropertiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering ({0}):   -&gt; [{1}].
        /// </summary>
        internal static string Discovering {
            get {
                return ResourceManager.GetString("Discovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while discovering tests: {0} ({1}).
        /// </summary>
        internal static string DiscoveryException {
            get {
                return ResourceManager.GetString("DiscoveryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while discovering tests for {0} ({1} - {2}).
        /// </summary>
        internal static string DiscoveryExceptionFor {
            get {
                return ResourceManager.GetString("DiscoveryExceptionFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0} ({1}).
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing:   -&gt; [{0}].
        /// </summary>
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable executor found for [{0}]..
        /// </summary>
        internal static string ExecutorNotFound {
            get {
                return ResourceManager.GetString("ExecutorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process could not be added to Job Object. Test process may end up orphaned on abrupt closure..
        /// </summary>
        internal static string FailedToAddProcess {
            get {
                return ResourceManager.GetString("FailedToAddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to terminate process {0}. Process may still be running..
        /// </summary>
        internal static string FailedToTerminateProcess {
            get {
                return ResourceManager.GetString("FailedToTerminateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding processes spawned by process with Id [{0}].
        /// </summary>
        internal static string FindingChildren {
            get {
                return ResourceManager.GetString("FindingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found test: {0}.
        /// </summary>
        internal static string FoundTest {
            get {
                return ResourceManager.GetString("FoundTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageDirectoryEntryToData failed!.
        /// </summary>
        internal static string ImageDirectoryEntryToData {
            get {
                return ResourceManager.GetString("ImageDirectoryEntryToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file defining property under {0}. {1}.
        /// </summary>
        internal static string InvalidPropertyFile {
            get {
                return ResourceManager.GetString("InvalidPropertyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list_content file: {0}.
        /// </summary>
        internal static string ListContentsFile {
            get {
                return ResourceManager.GetString("ListContentsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --list_content=DOT output for {0} is not available. Skipping..
        /// </summary>
        internal static string ListContentsNotFound {
            get {
                return ResourceManager.GetString("ListContentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file         : {0}.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger initialized. Logging to {0}.
        /// </summary>
        internal static string LoggerInitialized {
            get {
                return ResourceManager.GetString("LoggerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child process [{0}] does not exist..
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Paths are being used. Please note that test navigation from the Test Explorer window will not be available. To enable such functionality, the Use Full Paths setting under C++ -&gt; Advanced in the project&apos;s Property Page must be set to Yes (/FC)..
        /// </summary>
        internal static string RelativePathsInUse {
            get {
                return ResourceManager.GetString("RelativePathsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract test report from standard error [{0}] to report file [{1}] ({2}).
        /// </summary>
        internal static string ReportException {
            get {
                return ResourceManager.GetString("ReportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report file      : {0}.
        /// </summary>
        internal static string ReportFile {
            get {
                return ResourceManager.GetString("ReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;path&apos; argument is a reserved keyword.
        /// </summary>
        internal static string ReservedPath {
            get {
                return ResourceManager.GetString("ReservedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost Test result file was not found or is empty..
        /// </summary>
        internal static string ResultFileNotFound {
            get {
                return ResourceManager.GetString("ResultFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Boost Test Runner exceeded the timeout threshold of {0}.
        /// </summary>
        internal static string RunnerTimeout {
            get {
                return ResourceManager.GetString("RunnerTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StdErr file      : {0}.
        /// </summary>
        internal static string StdErrFile {
            get {
                return ResourceManager.GetString("StdErrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StdOut file      : {0}.
        /// </summary>
        internal static string StdOutFile {
            get {
                return ResourceManager.GetString("StdOutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while trying to delete temporary file [{0}].
        /// </summary>
        internal static string TempDeleteException {
            get {
                return ResourceManager.GetString("TempDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully terminated process {0}..
        /// </summary>
        internal static string TerminatedProcess {
            get {
                return ResourceManager.GetString("TerminatedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while running tests from {0} ({1}).
        /// </summary>
        internal static string TestException {
            get {
                return ResourceManager.GetString("TestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test setup error: no test cases matching filter (test name contains commas).
        /// </summary>
        internal static string TestNameContainsCommas {
            get {
                return ResourceManager.GetString("TestNameContainsCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test setup error: no test cases matching filter (test name contains spaces).
        /// </summary>
        internal static string TestNameContainsSpaces {
            get {
                return ResourceManager.GetString("TestNameContainsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test setup error: no test cases matching filter.
        /// </summary>
        internal static string TestNotFound {
            get {
                return ResourceManager.GetString("TestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout exceeded. Test ran for more than {0} ms..
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set information. Error: {0}.
        /// </summary>
        internal static string UnableToSetInformation {
            get {
                return ResourceManager.GetString("UnableToSetInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnMapAndLoad failed!.
        /// </summary>
        internal static string UnMapLoad {
            get {
                return ResourceManager.GetString("UnMapLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory: {0}.
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve WorkingDirectory from Visual Studio configuration.
        /// </summary>
        internal static string WorkingDirectoryNotFound {
            get {
                return ResourceManager.GetString("WorkingDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve WorkingDirectory from Visual Studio configuration: {0}.
        /// </summary>
        internal static string WorkingDirectoryNotFoundEx {
            get {
                return ResourceManager.GetString("WorkingDirectoryNotFoundEx", resourceCulture);
            }
        }
    }
}
